name: Update README with Bot Status

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install jq -y

      - name: Fetch Bot Status
        id: get_status
        run: |
          STATUS=$(curl -s http://54.39.8.32:25616/bot-status || echo '{"status":"offline"}')
          BOT_STATUS=$(echo $STATUS | jq -r '.status')
          echo "Fetched Bot Status: $BOT_STATUS"
          echo "status=$BOT_STATUS" >> $GITHUB_ENV

      - name: Update README
        run: |
          if [ "$status" = "online" ]; then
            STATUS_TEXT="🟢 Online"
          else
            STATUS_TEXT="🔴 Offline"
          fi
          echo "Before Update:"
          cat README.md
          sed -i "s/Bot Status: .*/Bot Status: $STATUS_TEXT/" README.md
          echo "After Update:"
          cat README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git checkout main
          git pull origin main
          git add README.md
          git commit -m "Update bot status: $status" || echo "No changes to commit"
          git push --force
